<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="6" total="15" passed="9">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="404406" started-at="2018-04-23T11:25:53Z" finished-at="2018-04-23T11:32:37Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="404406" started-at="2018-04-23T11:25:53Z" finished-at="2018-04-23T11:32:37Z">
      <class name="API_VootKids.ForgotPin">
        <test-method status="PASS" signature="Forgot_Pin()[pri:0, instance:API_VootKids.ForgotPin@617faa95]" name="Forgot_Pin" duration-ms="6731" started-at="2018-04-23T17:02:28Z" finished-at="2018-04-23T17:02:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Forgot_Pin -->
      </class> <!-- API_VootKids.ForgotPin -->
      <class name="API_VootKids.SignUp">
        <test-method status="PASS" signature="SignUp_Kids()[pri:0, instance:API_VootKids.SignUp@148080bb]" name="SignUp_Kids" duration-ms="36382" started-at="2018-04-23T17:01:22Z" finished-at="2018-04-23T17:01:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SignUp_Kids -->
      </class> <!-- API_VootKids.SignUp -->
      <class name="API_VootKids.CreatePin">
        <test-method status="FAIL" signature="CreatePin()[pri:0, instance:API_VootKids.CreatePin@1e127982]" name="CreatePin" duration-ms="2441" started-at="2018-04-23T17:02:35Z" finished-at="2018-04-23T17:02:37Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at API_VootKids.CreatePin.CreatePin(CreatePin.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreatePin -->
      </class> <!-- API_VootKids.CreatePin -->
      <class name="API_VootKids.GetChildProfiles">
        <test-method status="PASS" signature="Get_ChildProfiles()[pri:0, instance:API_VootKids.GetChildProfiles@55d56113]" name="Get_ChildProfiles" duration-ms="6737" started-at="2018-04-23T17:01:15Z" finished-at="2018-04-23T17:01:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Get_ChildProfiles -->
      </class> <!-- API_VootKids.GetChildProfiles -->
      <class name="API_VootKids.Tabs">
        <test-method status="PASS" signature="tabs()[pri:0, instance:API_VootKids.Tabs@dc24521]" name="tabs" duration-ms="411" started-at="2018-04-23T17:01:58Z" finished-at="2018-04-23T17:01:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tabs -->
      </class> <!-- API_VootKids.Tabs -->
      <class name="API_VootKids.Home">
        <test-method status="FAIL" signature="home()[pri:0, instance:API_VootKids.Home@7e0b0338]" name="home" duration-ms="17307" started-at="2018-04-23T17:02:11Z" finished-at="2018-04-23T17:02:28Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected [offSet must be at least 0.] but found [OK],
	expected object to not be null,
	expected object to not be null,
	expected [OK] but found [Invalid Uid],
	expected [OK] but found [Invalid Uid],
	expected [uId parameter is required] but found [Invalid Uid],
	expected [OK] but found [Invalid Profile Id],
	expected [OK] but found [Invalid Profile Id],
	expected [profileId parameter is required] but found [Invalid Profile Id],
	expected [OK] but found [Invalid Ks value],
	expected [ks parameter is required] but found [Invalid Ks value]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected object to not be null,
	expected [offSet must be at least 0.] but found [OK],
	expected object to not be null,
	expected object to not be null,
	expected [OK] but found [Invalid Uid],
	expected [OK] but found [Invalid Uid],
	expected [uId parameter is required] but found [Invalid Uid],
	expected [OK] but found [Invalid Profile Id],
	expected [OK] but found [Invalid Profile Id],
	expected [profileId parameter is required] but found [Invalid Profile Id],
	expected [OK] but found [Invalid Ks value],
	expected [ks parameter is required] but found [Invalid Ks value]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at API_VootKids.Home.home(Home.java:175)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- home -->
      </class> <!-- API_VootKids.Home -->
      <class name="API_VootKids.CreateProfile">
        <test-method status="FAIL" signature="Create_Profiles()[pri:0, instance:API_VootKids.CreateProfile@64bfbc86]" name="Create_Profiles" duration-ms="217126" started-at="2018-04-23T16:57:23Z" finished-at="2018-04-23T17:01:00Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [Client error: `POST https://rest-sgs1.ott.kaltura.com/restful_v4_4/api_v3/service/householddevice/action/add` resulted in a `404 Not Found` response:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xml (truncated...)
] but found [UserDoesNotExist],
	expected [Client error: `POST https://rest-sgs1.ott.kaltura.com/restful_v4_4/api_v3/service/householddevice/action/add` resulted in a `404 Not Found` response:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xml (truncated...)
] but found [UserDoesNotExist]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Client error: `POST https://rest-sgs1.ott.kaltura.com/restful_v4_4/api_v3/service/householddevice/action/add` resulted in a `404 Not Found` response:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xml (truncated...)
] but found [UserDoesNotExist],
	expected [Client error: `POST https://rest-sgs1.ott.kaltura.com/restful_v4_4/api_v3/service/householddevice/action/add` resulted in a `404 Not Found` response:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xml (truncated...)
] but found [UserDoesNotExist]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at API_VootKids.CreateProfile.Create_Profiles(CreateProfile.java:281)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Create_Profiles -->
      </class> <!-- API_VootKids.CreateProfile -->
      <class name="API_VootKids.ResetPin">
        <test-method status="FAIL" signature="reset_Pin()[pri:0, instance:API_VootKids.ResetPin@192b07fd]" name="reset_Pin" duration-ms="14486" started-at="2018-04-23T16:57:08Z" finished-at="2018-04-23T16:57:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [This custom field is invalid, please use a correct or valid custom field.] but found [Pin reset was successful.],
	expected [This custom field is invalid, please use a correct or valid custom field.] but found [Pin reset was successful.],
	expected [This custom field is invalid, please use a correct or valid custom field.] but found [The new pin must not same as old pin],
	expected [This custom field is invalid, please use a correct or valid custom field.] but found [invalid old pin]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [This custom field is invalid, please use a correct or valid custom field.] but found [Pin reset was successful.],
	expected [This custom field is invalid, please use a correct or valid custom field.] but found [Pin reset was successful.],
	expected [This custom field is invalid, please use a correct or valid custom field.] but found [The new pin must not same as old pin],
	expected [This custom field is invalid, please use a correct or valid custom field.] but found [invalid old pin]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at API_VootKids.ResetPin.reset_Pin(ResetPin.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reset_Pin -->
      </class> <!-- API_VootKids.ResetPin -->
      <class name="API_VootKids.UpdateProfile">
        <test-method status="PASS" signature="SignUp_Kids()[pri:0, instance:API_VootKids.UpdateProfile@49993335]" name="SignUp_Kids" duration-ms="33902" started-at="2018-04-23T16:56:21Z" finished-at="2018-04-23T16:56:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SignUp_Kids -->
      </class> <!-- API_VootKids.UpdateProfile -->
      <class name="API_VootKids.ForgotPassword">
        <test-method status="PASS" signature="Forgot_Password()[pri:0, instance:API_VootKids.ForgotPassword@5025a98f]" name="Forgot_Password" duration-ms="6363" started-at="2018-04-23T16:56:14Z" finished-at="2018-04-23T16:56:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Forgot_Password -->
      </class> <!-- API_VootKids.ForgotPassword -->
      <class name="API_VootKids.ResetPassword">
        <test-method status="FAIL" signature="reset_Password()[pri:0, instance:API_VootKids.ResetPassword@20322d26]" name="reset_Password" duration-ms="13651" started-at="2018-04-23T16:56:54Z" finished-at="2018-04-23T16:57:08Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [Password reset was successful.] but found [Invalid old password],
	expected [Your new password is too similar to your old passwords, please try a different password.] but found [OldPassword & NewPassword should not be same]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Password reset was successful.] but found [Invalid old password],
	expected [Your new password is too similar to your old passwords, please try a different password.] but found [OldPassword & NewPassword should not be same]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at API_VootKids.ResetPassword.reset_Password(ResetPassword.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reset_Password -->
      </class> <!-- API_VootKids.ResetPassword -->
      <class name="API_VootKids.SocialLogin">
        <test-method status="PASS" signature="Social_Login()[pri:0, instance:API_VootKids.SocialLogin@6e1ec318]" name="Social_Login" duration-ms="12005" started-at="2018-04-23T17:01:59Z" finished-at="2018-04-23T17:02:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Social_Login -->
      </class> <!-- API_VootKids.SocialLogin -->
      <class name="API_VootKids.Login">
        <test-method status="PASS" signature="Login_Kids()[pri:0, instance:API_VootKids.Login@5649fd9b]" name="Login_Kids" duration-ms="21126" started-at="2018-04-23T16:55:53Z" finished-at="2018-04-23T16:56:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_Kids -->
      </class> <!-- API_VootKids.Login -->
      <class name="API_VootKids.SwitchProfile">
        <test-method status="FAIL" signature="Swith_Profile()[pri:0, instance:API_VootKids.SwitchProfile@64bf3bbf]" name="Swith_Profile" duration-ms="15313" started-at="2018-04-23T17:01:00Z" finished-at="2018-04-23T17:01:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [Undefined index: user] but found [Invalid Uid],
	expected [Undefined index: user] but found [Invalid Uid],
	expected [Undefined index: user] but found [Invalid Uid],
	expected [Undefined index: user] but found [Invalid ChildProfileId],
	expected [Undefined index: user] but found [Invalid ChildProfileId],
	expected [Undefined index: user] but found [Invalid ChildProfileId]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Undefined index: user] but found [Invalid Uid],
	expected [Undefined index: user] but found [Invalid Uid],
	expected [Undefined index: user] but found [Invalid Uid],
	expected [Undefined index: user] but found [Invalid ChildProfileId],
	expected [Undefined index: user] but found [Invalid ChildProfileId],
	expected [Undefined index: user] but found [Invalid ChildProfileId]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at API_VootKids.SwitchProfile.Swith_Profile(SwitchProfile.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Swith_Profile -->
      </class> <!-- API_VootKids.SwitchProfile -->
      <class name="API_VootKids.Config">
        <test-method status="PASS" signature="config()[pri:0, instance:API_VootKids.Config@10bdf5e5]" name="config" duration-ms="389" started-at="2018-04-23T17:01:59Z" finished-at="2018-04-23T17:01:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config -->
      </class> <!-- API_VootKids.Config -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
